basePath: /
consumes:
- application/json
definitions:
  LoginResponse:
    description: LoginResponse defines the struct for API login
    properties:
      message:
        description: Contains user information
        properties:
          email:
            description: the user's email address
            type: string
            x-go-name: Email
          firstname:
            description: the user's first name
            type: string
            x-go-name: FirstName
          id:
            description: the user's id
            type: string
            x-go-name: ID
          lastname:
            description: the user's last name
            type: string
            x-go-name: LastName
          password:
            description: the user's hashed password
            type: string
            x-go-name: PassWord
        type: object
        x-go-name: Message
      status:
        description: shows if process was successful or not
        type: boolean
        x-go-name: Status
      token:
        description: A unique number that defines authenticates the users transactions
        type: string
        x-go-name: Token
    type: object
    x-go-package: github.com/IamNator/mysql-golang-web/session
  MyStdResp:
    properties:
      Status:
        description: successful / not successful
        type: boolean
      message:
        description: string
        type: object
        x-go-name: Message
    type: object
    x-go-package: github.com/IamNator/mysql-golang-web/session
info:
  contact:
    email: natverior1@gmail.com
  description: Documentation for register API
  title: Login API
  version: 1.0.0
paths:
  /api/login:
    post:
      description: Returns a session token
      operationId: login
      responses:
        "200":
          $ref: '#/responses/loginResponse'
        "404":
          $ref: '#/responses/loginNotFound'
      tags:
      - session
  /api/logout:
    post:
      description: logs the user out
      operationId: logout
      responses:
        "200":
          $ref: '#/responses/logoutResponse'
      tags:
      - session
  /api/register:
    post:
      description: adds new user to user database
      operationId: register
      responses:
        "200":
          $ref: '#/responses/registerResponse'
      tags:
      - session
produces:
- application/json
responses:
  loginNotFound:
    description: Non registered user tries to login
    schema:
      $ref: '#/definitions/MyStdResp'
  loginResponse:
    description: Successful login request
    schema:
      $ref: '#/definitions/LoginResponse'
  logoutResponse:
    description: ""
    schema:
      $ref: '#/definitions/MyStdResp'
  registerResponse:
    description: ""
    schema:
      $ref: '#/definitions/MyStdResp'
schemes:
- http
swagger: "2.0"
