basePath: /
consumes:
- application/json
definitions:
  LoginResponse:
    properties:
      message:
        properties:
          email:
            type: string
            x-go-name: Email
          firstname:
            type: string
            x-go-name: FirstName
          id:
            type: string
            x-go-name: ID
          lastname:
            type: string
            x-go-name: LastName
          password:
            type: string
            x-go-name: PassWord
        type: object
        x-go-name: Message
      status:
        type: boolean
        x-go-name: Status
      token:
        type: string
        x-go-name: Token
    type: object
    x-go-package: github.com/IamNator/mysql-golang-web/session
info:
  description: Documentation for Login API
  title: Login API
  version: 1.0.0
paths:
  /api/login:
    get:
      description: Returns a session token
      operationId: login
      responses:
        "200":
          description: LoginResponse
          schema:
            $ref: '#/definitions/LoginResponse'
      tags:
      - session
produces:
- application/json
responses:
  login:
    description: Respond to login request
    schema:
      items:
        $ref: '#/definitions/LoginResponse'
      type: array
schemes:
- http
swagger: "2.0"
