basePath: /
consumes:
- application/json
definitions:
  LoginResponse:
    properties:
      message:
        properties:
          email:
            type: string
            x-go-name: Email
          firstname:
            type: string
            x-go-name: FirstName
          id:
            type: string
            x-go-name: ID
          lastname:
            type: string
            x-go-name: LastName
          password:
            type: string
            x-go-name: PassWord
        type: object
        x-go-name: Message
      status:
        type: boolean
        x-go-name: Status
      token:
        type: string
        x-go-name: Token
    type: object
    x-go-package: github.com/IamNator/mysql-golang-web/session
  MyStdResp:
    properties:
      Message:
        type: object
      Status:
        type: boolean
    type: object
    x-go-package: github.com/IamNator/mysql-golang-web/session
info:
  description: Documentation for Login API
  title: Login API
  version: 1.0.0
paths:
  /api/login:
    get:
      description: Returns a session token
      operationId: login
      responses:
        "200":
          $ref: '#/responses/loginResponse'
        "404":
          $ref: '#/responses/loginNotFound'
      tags:
      - session
produces:
- application/json
responses:
  loginNotFound:
    description: Non registered user tries to login
    schema:
      $ref: '#/definitions/MyStdResp'
  loginResponse:
    description: Successful login request
    schema:
      $ref: '#/definitions/LoginResponse'
schemes:
- http
swagger: "2.0"
